# Generated by Django 4.1.5 on 2023-02-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.CharField(max_length=100)),
                ('BatteryVolume', models.IntegerField()),
                ('CPU', models.CharField(max_length=100)),
                ('DRam', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MissionName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SemanticSegmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelName', models.CharField(max_length=100, null=True)),
                ('Flops', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Params', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Storage', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Energy', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('MissionName2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hmt.mission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelName', models.CharField(max_length=100, null=True)),
                ('Flops', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Params', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Storage', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Energy', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('Accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('MissionName2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hmt.mission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
