# Generated by Django 4.1.5 on 2023-02-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageclassification',
            name='CompressRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='semanticsegmentation',
            name='CompressRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
