# Generated by Django 4.1.5 on 2023-02-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmt', '0002_imageclassification_compressrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclassification',
            name='CompressRate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='Flops',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='Params',
            field=models.DecimalField(decimal_places=2, default=1.22, max_digits=100),
        ),
        migrations.AlterField(
            model_name='semanticsegmentation',
            name='CompressRate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='semanticsegmentation',
            name='Flops',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='semanticsegmentation',
            name='Params',
            field=models.DecimalField(decimal_places=2, default=1.22, max_digits=100),
        ),
    ]
