# Generated by Django 4.1.5 on 2023-02-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmt', '0003_alter_imageclassification_compressrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclassification',
            name='Accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='Energy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='Flops',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='Params',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='Storage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='semanticsegmentation',
            name='Accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='semanticsegmentation',
            name='Energy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='semanticsegmentation',
            name='Flops',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='semanticsegmentation',
            name='Params',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='semanticsegmentation',
            name='Storage',
            field=models.FloatField(default=0.0),
        ),
    ]
